CREATE SET TABLE ADLSTE_WestComm.Consumption_IO_Forecast_V2 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SiteID VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      "Report Date" DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      "Log Date" DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      "Peak Start" VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      "Peak End" VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      "Avg IO Pct" DECIMAL(18,4),
      "Moving Avg" DECIMAL(18,4),
      Trend DECIMAL(18,4),
      ReserveX DECIMAL(18,4),
      "Reserve Horizon" DECIMAL(18,4),
      SlopeX DECIMAL(18,4))
UNIQUE PRIMARY INDEX ( SiteID ,"Report Date" ,"Log Date" );
