
CREATE MULTISET GLOBAL TEMPORARY TABLE ADLSTE_WestComm.consumption_cpu_forecast_stg ,FALLBACK ,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     LOG
     (
      SiteID VARCHAR(1024) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Report Date" VARCHAR(1024) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Log Date" VARCHAR(1024) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Peak Start" VARCHAR(1024) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Peak End" VARCHAR(1024) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Avg CPU Pct" FLOAT,
      "Moving Avg" FLOAT,
      Trend FLOAT,
      ReserveX BIGINT,
      "Reserve Horizon" FLOAT,
      SlopeX FLOAT)
PRIMARY INDEX ( SiteID ,"Report Date" ,"Log Date" )
ON COMMIT PRESERVE ROWS;
