/* TCA Process for ResUsageSVPR == 1620 */ 
/*  Parameters:
     startdate = {startdate}
     enddate = {enddate}
     resusagesvpr = {resusagesvpr}
     dbprefix = {dbprefix} <-- probably blank, but set to "Dev_" in the FileSet during TCA Testing
     dbsversion_label = {dbsversion_label}
 */
 
/*{{save:tca_resusageSVPR_{dbsversion_label}.csv}}*/
/*{{load:{dbprefix}APP_TCA_TMP.stg_tca_resusageSVPR_{dbsversion_label}}}*/
/*{{call:{dbprefix}APP_TCA_TBL.sp_tca_resusageSVPR_{dbsversion_label}()}}*/
Select 
  '{siteid}' as Site_ID
 ,TheDate as TheDate
 ,NodeID as NodeID
 ,TheTime as TheTime
 ,NULL as GmtTime
 ,NULL as CabinetID
 ,NULL as ModuleID
 ,NULL as NodeType
 ,NULL as TheTimestamp
 ,NULL as CentiSecs
 ,NULL as Secs
 ,NULL as NominalSecs
 ,NULL as SummaryFlag
 ,NULL as Reserved
 ,NULL as PM_COD_CPU
 ,NULL as WM_COD_CPU
 ,NULL as NCPUs
 ,NULL as vprid
 ,case when VprType like 'PE%' then 'PE' when VprType like 'GTW%' then 'GTW' when VprType like 'AMP%' then 'AMP' else 'OTHER' end as VprType
 ,NULL as MemPDbKBResCU
 ,NULL as MemPCiKBResCU
 ,NULL as MemSDbKBResCU
 ,NULL as MemSCiKBResCU
 ,NULL as MemTJtKBResCU
 ,NULL as MemAPtKBResCU
 ,NULL as MemPDbKBResDU
 ,NULL as MemPCiKBResDU
 ,NULL as MemSDbKBResDU
 ,NULL as MemSCiKBResDU
 ,NULL as MemTJtKBResDU
 ,NULL as MemAPtKBResDU
 ,NULL as MemPDbKBResCA
 ,NULL as MemPCiKBResCA
 ,NULL as MemSDbKBResCA
 ,NULL as MemSCiKBResCA
 ,NULL as MemTJtKBResCA
 ,NULL as MemAPtKBResCA
 ,NULL as MemPDbKBResDA
 ,NULL as MemPCiKBResDA
 ,NULL as MemSDbKBResDA
 ,NULL as MemSCiKBResDA
 ,NULL as MemTJtKBResDA
 ,NULL as MemAPtKBResDA
 ,NULL as MemCtxtAccessKB
 ,NULL as MemCtxtDeaccessKB
 ,NULL as MemCtxtDestroyKB
 ,NULL as NetPtPReadKB
 ,NULL as NetPtPWriteKB
 ,NULL as NetBrdReadKB
 ,NULL as NetBrdWriteKB
 ,sum(FilePDbAcqKB) as FilePDbAcqKB
 ,sum(FilePCiAcqKB) as FilePCiAcqKB
 ,sum(FileSDbAcqKB) as FileSDbAcqKB
 ,sum(FileSCiAcqKB) as FileSCiAcqKB
 ,NULL as FileTJtAcqKB
 ,NULL as FileAPtAcqKB
 ,NULL as FilePDbAcqOtherKB
 ,NULL as FilePCiAcqOtherKB
 ,NULL as FileSDbAcqOtherKB
 ,NULL as FileSCiAcqOtherKB
 ,NULL as FileTJtAcqOtherKB
 ,NULL as FileAPtAcqOtherKB
 ,NULL as FilePDbRelOtherKB
 ,NULL as FilePCiRelOtherKB
 ,NULL as FileSDbRelOtherKB
 ,NULL as FileSCiRelOtherKB
 ,NULL as FileTJtRelOtherKB
 ,NULL as FileAPtRelOtherKB
 ,NULL as FilePDbAcqReadKB
 ,sum(FilePCiAcqReadKB) as FilePCiAcqReadKB
 ,NULL as FileSDbAcqReadKB
 ,sum(FileSCiAcqReadKB) as FileSCiAcqReadKB
 ,sum(FileTJtAcqReadKB) as FileTJtAcqReadKB
 ,NULL as FileAPtAcqReadKB
 ,NULL as FilePDbPresKB
 ,NULL as FilePCiPresKB
 ,NULL as FileSDbPresKB
 ,NULL as FileSCiPresKB
 ,NULL as FileTJtPresKB
 ,NULL as FileAPtPresKB
 ,NULL as FilePDbPreReadKB
 ,sum(FilePCiPreReadKB) as FilePCiPreReadKB
 ,NULL as FileSDbPreReadKB
 ,sum(FileSCiPreReadKB) as FileSCiPreReadKB
 ,sum(FileTJtPreReadKB) as FileTJtPreReadKB
 ,NULL as FileAPtPreReadKB
 ,sum(FilePDbDyRRelKB) as FilePDbDyRRelKB
 ,NULL as FilePCiDyRRelKB
 ,sum(FileSDbDyRRelKB) as FileSDbDyRRelKB
 ,NULL as FileSCiDyRRelKB
 ,NULL as FileTJtDyRRelKB
 ,NULL as FileAPtDyRRelKB
 ,NULL as FilePDbFWriteKB
 ,sum(FilePCiFWriteKB) as FilePCiFWriteKB
 ,NULL as FileSDbFWriteKB
 ,sum(FileSCiFWriteKB) as FileSCiFWriteKB
 ,sum(FileTJtFWriteKB) as FileTJtFWriteKB
 ,NULL as FileAPtFWriteKB
 ,sum(FilePDbDyAWriteKB) as FilePDbDyAWriteKB
 ,NULL as FilePCiDyAWriteKB
 ,sum(FileSDbDyAWriteKB) as FileSDbDyAWriteKB
 ,NULL as FileSCiDyAWriteKB
 ,sum(FileTJtDyAWriteKB) as FileTJtDyAWriteKB
 ,NULL as FileAPtDyAWriteKB
 ,sum(FilePDbCnRRelKB) as FilePDbCnRRelKB
 ,NULL as FilePCiCnRRelKB
 ,sum(FileSDbCnRRelKB) as FileSDbCnRRelKB
 ,NULL as FileSCiCnRRelKB
 ,NULL as FileTJtCnRRelKB
 ,NULL as FileAPtCnRRelKB
 ,NULL as FilePDbFDrpKB
 ,NULL as FilePCiFDrpKB
 ,NULL as FileSDbFDrpKB
 ,NULL as FileSCiFDrpKB
 ,NULL as FileTJtFDrpKB
 ,NULL as FileAPtFDrpKB
 ,NULL as FilePDbCnADrpKB
 ,NULL as FilePCiCnADrpKB
 ,NULL as FileSDbCnADrpKB
 ,NULL as FileSCiCnADrpKB
 ,NULL as FileTJtCnADrpKB
 ,NULL as FileAPtCnADrpKB
 ,NULL as ReadResponseHotTotal
 ,NULL as ReadResponseWarmTotal
 ,NULL as ReadResponseColdTotal
 ,NULL as WriteResponseHotTotal
 ,NULL as WriteResponseWarmTotal
 ,NULL as WriteResponseColdTotal
 ,sum(FilePreCompMB) as FilePreCompMB
 ,sum(FilePostCompMB) as FilePostCompMB
 ,sum(FilePreUnCompMB) as FilePreUnCompMB
 ,sum(FilePostUnCompMB) as FilePostUnCompMB
 ,sum(FileCompCPU) as FileCompCPU
 ,sum(FileUnCompCPU) as FileUnCompCPU
 ,NULL as FileTempCPU
 ,sum(VHAgedOut) as VHAgedOut
 ,sum(VHAgedOutKB) as VHAgedOutKB
 ,sum(VHLogicalDBRead) as VHLogicalDBRead
 ,sum(VHLogicalDBReadKB) as VHLogicalDBReadKB
 ,sum(VHPhysicalDBRead) as VHPhysicalDBRead
 ,sum(VHPhysicalDBReadKB) as VHPhysicalDBReadKB
 ,NULL as VHCacheInuseKB
 ,NULL as FsgCacheInuseKB
 ,NULL as SpaceAllocated
 ,NULL as SpaceDeallocated
 ,NULL as Spare00
 ,NULL as Spare01
 ,NULL as Spare02
 ,NULL as Spare03
 ,NULL as Spare04
 ,NULL as Spare05
 ,NULL as Spare06
 ,NULL as Spare07
 ,NULL as Spare08
 ,NULL as Spare09
 ,NULL as Spare10
 ,NULL as Spare11
 ,NULL as Spare12
 ,NULL as Spare13
 ,NULL as Spare14
 ,NULL as Spare15
 ,NULL as Spare16
 ,NULL as Spare17
 ,NULL as Spare18
 ,NULL as Spare19
 ,NULL as Spare20
 ,NULL as Spare21
 ,NULL as Spare22
 ,NULL as Spare23
 ,NULL as Spare24
 ,NULL as Spare25
 ,NULL as Spare26
 ,NULL as Spare27
 ,NULL as Spare28
 ,NULL as Spare29
 ,NULL as Active
 ,NULL as ProcPendDBLock
 ,NULL as ProcBlksDBLock
 ,NULL as ProcWaitDBLock
 ,NULL as MemCtxtAllocs
 ,NULL as MemCtxtAccesses
 ,NULL as MemCtxtDeaccesses
 ,NULL as MemCtxtDestroys
 ,NULL as NetPtPReads
 ,NULL as NetPtPWrites
 ,NULL as NetBrdReads
 ,NULL as NetBrdWrites
 ,NULL as DBLockEnters
 ,NULL as DBLockBlocks
 ,NULL as DBLockDeadlocks
 ,sum(FilePDbAcqs) as FilePDbAcqs
 ,sum(FilePCiAcqs) as FilePCiAcqs
 ,sum(FileSDbAcqs) as FileSDbAcqs
 ,sum(FileSCiAcqs) as FileSCiAcqs
 ,NULL as FileTJtAcqs
 ,NULL as FileAPtAcqs
 ,NULL as FilePDbAcqsOther
 ,NULL as FilePCiAcqsOther
 ,NULL as FileSDbAcqsOther
 ,NULL as FileSCiAcqsOther
 ,NULL as FileTJtAcqsOther
 ,NULL as FileAPtAcqsOther
 ,NULL as FilePDbRelsOther
 ,NULL as FilePCiRelsOther
 ,NULL as FileSDbRelsOther
 ,NULL as FileSCiRelsOther
 ,NULL as FileTJtRelsOther
 ,NULL as FileAPtRelsOther
 ,sum(FilePDbAcqReads) as FilePDbAcqReads
 ,sum(FilePCiAcqReads) as FilePCiAcqReads
 ,sum(FileSDbAcqReads) as FileSDbAcqReads
 ,sum(FileSCiAcqReads) as FileSCiAcqReads
 ,NULL as FileTJtAcqReads
 ,NULL as FileAPtAcqReads
 ,NULL as FilePDbPres
 ,NULL as FilePCiPres
 ,NULL as FileSDbPres
 ,NULL as FileSCiPres
 ,NULL as FileTJtPres
 ,NULL as FileAPtPres
 ,sum(FilePDbPreReads) as FilePDbPreReads
 ,sum(FilePCiPreReads) as FilePCiPreReads
 ,sum(FileSDbPreReads) as FileSDbPreReads
 ,sum(FileSCiPreReads) as FileSCiPreReads
 ,NULL as FileTJtPreReads
 ,NULL as FileAPtPreReads
 ,sum(FilePDbDyRRels) as FilePDbDyRRels
 ,NULL as FilePCiDyRRels
 ,sum(FileSDbDyRRels) as FileSDbDyRRels
 ,NULL as FileSCiDyRRels
 ,NULL as FileTJtDyRRels
 ,NULL as FileAPtDyRRels
 ,NULL as FilePDbFWrites
 ,sum(FilePCiFWrites) as FilePCiFWrites
 ,NULL as FileSDbFWrites
 ,sum(FileSCiFWrites) as FileSCiFWrites
 ,NULL as FileTJtFWrites
 ,NULL as FileAPtFWrites
 ,sum(FilePDbDyAWrites) as FilePDbDyAWrites
 ,NULL as FilePCiDyAWrites
 ,NULL as FileSDbDyAWrites
 ,NULL as FileSCiDyAWrites
 ,NULL as FileTJtDyAWrites
 ,NULL as FileAPtDyAWrites
 ,sum(FilePDbCnRRels) as FilePDbCnRRels
 ,NULL as FilePCiCnRRels
 ,sum(FileSDbCnRRels) as FileSDbCnRRels
 ,NULL as FileSCiCnRRels
 ,NULL as FileTJtCnRRels
 ,NULL as FileAPtCnRRels
 ,NULL as FilePDbFDrps
 ,NULL as FilePCiFDrps
 ,NULL as FileSDbFDrps
 ,NULL as FileSCiFDrps
 ,NULL as FileTJtFDrps
 ,NULL as FileAPtFDrps
 ,NULL as FilePDbCnADrps
 ,NULL as FilePCiCnADrps
 ,NULL as FileSDbCnADrps
 ,NULL as FileSCiCnADrps
 ,NULL as FileTJtCnADrps
 ,NULL as FileAPtCnADrps
 ,NULL as FileLockEnters
 ,NULL as FileLockBlocks
 ,NULL as FileLockDeadlocks
 ,NULL as FileCylMigrs
 ,NULL as FileCylAllocs
 ,NULL as FileCylFrees
 ,NULL as FileMCylPacks
 ,NULL as FileCylDefrags
 ,NULL as FileWCylAllocs
 ,NULL as FileWCylFrees
 ,sum(FileFcrRequests) as FileFcrRequests
 ,NULL as FileFcrRequestsAdaptive
 ,sum(FileFcrDeniedUser) as FileFcrDeniedUser
 ,sum(FileFcrDeniedCache) as FileFcrDeniedCache
 ,sum(FileFcrDeniedThreshUser) as FileFcrDeniedThreshUser
 ,sum(FileFcrBlocksRead) as FileFcrBlocksRead
 ,NULL as FileFcrBlocksDeniedUser
 ,NULL as FileFcrBlocksDeniedCache
 ,NULL as FileFcrBlocksDeniedThreshUser
 ,sum(FileFcrDeniedKern) as FileFcrDeniedKern
 ,NULL as FileFcrDeniedThreshKern
 ,NULL as FileFcrBlocksDeniedKern
 ,NULL as FileFcrBlocksDeniedThreshKern
 ,NULL as FileSyncScans
 ,NULL as FileSyncSubtables
 ,NULL as FileSyncScanners
 ,NULL as FileSyncGroups
 ,NULL as MsgWorkQLenMax
 ,NULL as MsgChnLastDone
 ,NULL as MsgWorkQLen
 ,NULL as CPUUServPart00
 ,NULL as CPUUServPart01
 ,NULL as CPUUServPart02
 ,NULL as CPUUServPart03
 ,NULL as CPUUServPart04
 ,NULL as CPUUServPart05
 ,NULL as CPUUServPart06
 ,NULL as CPUUServPart07
 ,NULL as CPUUServPart08
 ,NULL as CPUUServPart09
 ,sum(CPUUServPart10) as CPUUServPart10
 ,sum(CPUUServPart11) as CPUUServPart11
 ,sum(CPUUServPart12) as CPUUServPart12
 ,sum(CPUUServPart13) as CPUUServPart13
 ,sum(CPUUServPart14) as CPUUServPart14
 ,NULL as CPUUServPart15
 ,NULL as CPUUServPart16
 ,NULL as CPUUServPart17
 ,NULL as CPUUServPart18
 ,NULL as CPUUServPart19
 ,NULL as CPUUServPart20
 ,NULL as CPUUServPart21
 ,NULL as CPUUServPart22
 ,NULL as CPUUServPart23
 ,NULL as CPUUServPart24
 ,NULL as CPUUServPart25
 ,NULL as CPUUServPart26
 ,NULL as CPUUServPart27
 ,NULL as CPUUServPart28
 ,NULL as CPUUServPart29
 ,NULL as CPUUServPart30
 ,NULL as CPUUServPart31
 ,NULL as CPUUServPart32
 ,NULL as CPUUServPart33
 ,NULL as CPUUServPart34
 ,NULL as CPUUServPart35
 ,NULL as CPUUServPart36
 ,NULL as CPUUServPart37
 ,NULL as CPUUServPart38
 ,NULL as CPUUServPart39
 ,NULL as CPUUServPart40
 ,NULL as CPUUServPart41
 ,NULL as CPUUServPart42
 ,NULL as CPUUServPart43
 ,NULL as CPUUServPart44
 ,NULL as CPUUServPart45
 ,NULL as CPUUServPart46
 ,NULL as CPUUServPart47
 ,NULL as CPUUExecPart00
 ,NULL as CPUUExecPart01
 ,NULL as CPUUExecPart02
 ,NULL as CPUUExecPart03
 ,NULL as CPUUExecPart04
 ,NULL as CPUUExecPart05
 ,NULL as CPUUExecPart06
 ,NULL as CPUUExecPart07
 ,NULL as CPUUExecPart08
 ,NULL as CPUUExecPart09
 ,sum(CPUUExecPart10) as CPUUExecPart10
 ,sum(CPUUExecPart11) as CPUUExecPart11
 ,sum(CPUUExecPart12) as CPUUExecPart12
 ,sum(CPUUExecPart13) as CPUUExecPart13
 ,sum(CPUUExecPart14) as CPUUExecPart14
 ,NULL as CPUUExecPart15
 ,NULL as CPUUExecPart16
 ,NULL as CPUUExecPart17
 ,NULL as CPUUExecPart18
 ,NULL as CPUUExecPart19
 ,NULL as CPUUExecPart20
 ,NULL as CPUUExecPart21
 ,NULL as CPUUExecPart22
 ,NULL as CPUUExecPart23
 ,NULL as CPUUExecPart24
 ,NULL as CPUUExecPart25
 ,NULL as CPUUExecPart26
 ,NULL as CPUUExecPart27
 ,NULL as CPUUExecPart28
 ,NULL as CPUUExecPart29
 ,NULL as CPUUExecPart30
 ,NULL as CPUUExecPart31
 ,NULL as CPUUExecPart32
 ,NULL as CPUUExecPart33
 ,NULL as CPUUExecPart34
 ,NULL as CPUUExecPart35
 ,NULL as CPUUExecPart36
 ,NULL as CPUUExecPart37
 ,NULL as CPUUExecPart38
 ,NULL as CPUUExecPart39
 ,NULL as CPUUExecPart40
 ,NULL as CPUUExecPart41
 ,NULL as CPUUExecPart42
 ,NULL as CPUUExecPart43
 ,NULL as CPUUExecPart44
 ,NULL as CPUUExecPart45
 ,NULL as CPUUExecPart46
 ,NULL as CPUUExecPart47
 ,NULL as AllocatorExtentAllocReqs
 ,NULL as AllocatorExtentFreeReqs
 ,NULL as AllocatorMapIOsStarted
 ,NULL as AllocatorMapIOsDone
 ,NULL as NodeAgentMigrationsStarted
 ,NULL as NodeAgentMigrationsDone
 ,NULL as NodeAgentStatProcessed
 ,NULL as ReadsHot
 ,NULL as ReadsWarm
 ,NULL as ReadsCold
 ,NULL as WritesHot
 ,NULL as WritesWarm
 ,NULL as WritesCold
 ,NULL as ReadResponseHotMax
 ,NULL as ReadResponseWarmMax
 ,NULL as ReadResponseColdMax
 ,NULL as WriteResponseHotMax
 ,NULL as WriteResponseWarmMax
 ,NULL as WriteResponseColdMax
 ,NULL as ReadResponseHotMin
 ,NULL as ReadResponseWarmMin
 ,NULL as ReadResponseColdMin
 ,NULL as WriteResponseHotMin
 ,NULL as WriteResponseWarmMin
 ,NULL as WriteResponseColdMin
 ,NULL as IoRespMax
 ,NULL as MIWriteLocks
 ,NULL as MIWriteLockTime
 ,NULL as MIWriteLockTimeMax
 ,NULL as MISleeps
 ,NULL as MISleepTime
 ,NULL as MISleepTimeMax
 ,NULL as DBMergeTried
 ,NULL as DBMergeDone
 ,NULL as DBMergeElim
 ,NULL as DBMergeExtraIO
 ,NULL as FileACPCylsSkipped
 ,NULL as FileACPCylsMigr
 ,NULL as FileACPCylsUnFSEOnly
 ,NULL as FileACPCylsPostponed
 ,sum(FileCompDBs) as FileCompDBs
 ,sum(FileUnCompDBs) as FileUnCompDBs
 ,NULL as FileCompFerretDBs
 ,NULL as FileUnCompFerretDBs
 ,NULL as FileCompTempDBs
 ,NULL as FileUncompTempDBs
 ,NULL as FileCompCylMigrs
 ,NULL as FileUnCompCylMigrs
 ,NULL as FsgCacheWaits
 ,NULL as FsgCacheWaitTime
 ,NULL as FsgCacheWaitTimeMax
 ,NULL as UdfServ
 ,NULL as UdfExec
 ,NULL as FileSorts
 ,NULL as FileLargeMemSorts
 ,NULL as FileLargeMemSortsDenied
 ,NULL as FileWALBufBusy
 ,NULL as FileWALSize
 ,NULL as SpaceProactiveAllocs
 ,NULL as SpaceGroupAllocs
 ,NULL as SpaceMsgsCnt
 ,NULL as FileCompDBs_HW
 ,NULL as FileUnCompDBs_HW
 ,NULL as SpareInt
from {resusagesvpr} -- pdcrinfo.resusageSVPR_hst or dbc.resusageSVPR
where TheDate between {startdate} and {enddate}
group by 
  '{siteid}'
 ,TheDate
 ,NodeID
 ,TheTime
 ,case when VprType like 'PE%' then 'PE' when VprType like 'GTW%' then 'GTW' when VprType like 'AMP%' then 'AMP' else 'OTHER' end
;